version: '3.7'

services:  
  pg-db:
    image: postgres
    restart: always
    container_name: pg-db
    hostname: pg-db
    environment:
      POSTGRES_PASSWORD: Mohamed
    volumes:
      - ./databases:/usr/databases
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "mohamedamged@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Mohamed"
    volumes:
      - ./databases:/usr/databases
    restart: always
    ports:
      - "5050:80"

    